import { _ } from '../helper.js'

export default {
  adminPasswordWrong: _('管理密码错误', 'Incorrect admin password', '管理密碼錯誤', '管理パスワードが違います', '관리자 비밀번호가 올바르지 않습니다', 'Sai mật khẩu quản trị', 'Contraseña de administrador incorrecta', 'Senha de administrador incorreta', 'Неверный пароль администратора', 'Mot de passe administrateur incorrect', 'Falsches Admin-Passwort'),
  adminRequired: _('需要管理员权限', 'Administrator permission required', '需要管理員權限', '管理者権限が必要です', '관리자 권한이 필요합니다', 'Cần quyền quản trị', 'Se requieren permisos de administrador', 'Permissão de administrador necessária', 'Требуются права администратора', 'Autorisation administrateur requise', 'Administratorberechtigung erforderlich'),
  announcementPrompt: _('输入新公告', 'Enter a new announcement', '輸入新公告', '新しいお知らせを入力', '새 공지를 입력하세요', 'Nhập thông báo mới', 'Introduce un nuevo anuncio', 'Digite um novo aviso', 'Введите новое объявление', 'Saisissez une nouvelle annonce', 'Neue Ankündigung eingeben'),
  deleteAnnouncementConfirm: _('确定删除当前公告？', 'Delete the current announcement?', '確定刪除目前公告？', '現在のお知らせを削除しますか？', '현재 공지를 삭제할까요?', 'Xóa thông báo hiện tại?', '¿Eliminar el anuncio actual?', 'Excluir o aviso atual?', 'Удалить текущее объявление?', 'Supprimer l’annonce actuelle ?', 'Aktuelle Ankündigung löschen?'),
  announcementDeleted: _('管理员已删除公告。', 'The administrator deleted the announcement.', '管理員已刪除公告。', '管理者がお知らせを削除しました。', '관리자가 공지를 삭제했습니다.', 'Quản trị viên đã xóa thông báo.', 'El administrador eliminó el anuncio.', 'O administrador excluiu o aviso.', 'Администратор удалил объявление.', 'L’administrateur a supprimé l’annonce.', 'Der Administrator hat die Ankündigung gelöscht.'),
  clearRoomConfirm: _('确定清空当前房间？', 'Clear the current room?', '確定清空目前房間？', '現在のルームをクリアしますか？', '현재 방을 비울까요?', 'Xóa sạch phòng hiện tại?', '¿Vaciar la sala actual?', 'Limpar a sala atual?', 'Очистить текущую комнату?', 'Vider le salon actuel ?', 'Aktuellen Raum leeren?'),
  saved: _('已保存', 'Saved', '已儲存', '保存しました', '저장됨', 'Đã lưu', 'Guardado', 'Salvo', 'Сохранено', 'Enregistré', 'Gespeichert'),
  muted: _('当前已开启全员禁言', 'All-member mute is currently enabled', '目前已開啟全員禁言', '現在全員ミュートが有効です', '현재 전체 음소거가 켜져 있습니다', 'Hiện đang bật cấm chat toàn phòng', 'El silencio global está activado', 'O silenciamento geral está ativado', 'Сейчас включён общий запрет сообщений', 'Le mode silence global est activé', 'Alle sind derzeit stummgeschaltet'),
  bannedWordHit: _('消息包含违禁词：{word}', 'Message contains a banned word: {word}', '訊息包含違禁詞：{word}', 'メッセージに禁止語が含まれています：{word}', '메시지에 금칙어가 포함되어 있습니다: {word}', 'Tin nhắn chứa từ bị cấm: {word}', 'El mensaje contiene una palabra prohibida: {word}', 'A mensagem contém uma palavra proibida: {word}', 'Сообщение содержит запрещённое слово: {word}', 'Le message contient un mot interdit : {word}', 'Nachricht enthält ein gesperrtes Wort: {word}'),
}
